### ISSUE TITLE
Strip trailing whitespace after removing include guards

### ISSUE THREAD

**Issue by cgmb** [cgmb/guardonce#10]
It would be nice to have a flag for this. I try to ensure guardonce makes minimal changes to the files it touches, but removing the guards without removing the surrounding whitespace may violate style conventions. The [Qt Creator changeover](https://codereview.qt-project.org/#/c/153286/) is a concrete example of a time when this would have been helpful.

**Comment by bjorn** [comment]
Missed this too, but Sublime Text helped me out with a regular expression like `/\n\n\Z/\n/`. :-)

**Comment by cgmb** [comment]
Hey! Thank you for the feedback. I'm glad you found guardonce useful. [I tried out Tiled a couple years ago, and I was quite impressed](https://github.com/jvamosi/Diversibee/issues/128).

**Comment by bjorn** [comment]
@cgmb Thanks!

Diversibee looks like an interesting project as well. :-)
