### ISSUE TITLE
Add processing another guard case

### ISSUE THREAD

**Issue by Reishu** [cgmb/guardonce#30]
Add processing another guard case
for example from our legacy

#if !defined(CONVERTER_H)
#define CONVERTER_H

**Comment by cgmb** [comment]
That should be pretty straightforward to add in `guard2once` and `checkguard`. I'll add support for that style and maybe cut a release next week.

If you were to convert back to guards in the future, would `#ifndef` be acceptable? Or is there something important about `#if !defined`? If the difference is unimportant, I might not bother adding the ability to generate that style of guard to `once2guard`.

**Comment by Reishu** [comment]
Convert back unimportant.  `ifndef `fully equal `#if !defined`. Our legacy have mix of this ( very old code. many bad practice )
