### ISSUE TITLE
cp1251 file processing/autodetect encoding as an option

### ISSUE THREAD

**Issue by Reishu** [cgmb/guardonce#31]
Can you add cp1251 file processing as option? or autodetect encdoing as option?

**Comment by cgmb** [comment]
That would be a good addition. At the moment, only UTF-8 inputs and outputs are officially supported, but I believe that works unofficially under the right conditions.

Under Python 2.7, guardonce should work fine for any ASCII-compatible encoding, including cp1251. The output will be in the same encoding as the input.

Under Python 3.5+, only UTF-8 input files are supported. I've been meaning to change this behaviour to match Python 2. However, there's a lot of testing required, so I have been putting it off.
